[phases.setup]
nixPkgs = ["python312", "postgresql"]

[phases.install]
cmds = [
  "python -m venv /opt/venv",
  ". /opt/venv/bin/activate && pip install --upgrade pip",
  ". /opt/venv/bin/activate && pip install -r requirements.prod.txt"
]

[start]
cmd = ". /opt/venv/bin/activate && python database.py && python create_admin_simple.py && python app.py"
